apiVersion: v2
appVersion: v0.1.0
description: Deploy the ArgoCD Platform. This chart is never packaged up but gets used via `helm template` command.
name: glueops-platform
version: 0.1.0
dependencies:
  - name: argo-cd
    version: 5.22.0
    repository: https://argoproj.github.io/argo-helm
    condition: argo-cd.glueops_is_argo_cd_enabled
