# Default values for glueops-argocd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



gitHub:
  sshKey: "base64-ssh-key"
  credentialTemplateUrl: "Z2l0QGdpdGh1Yi5jb20=" #git@github.com
  k8sBootstrapRepo: "base64-encoded-string" #git@github.com:GlueOps/platform.git
  customer_github_org_and_team: "org:team"



externalDns:
  cloudflare_api_token: nil

certManager:
  cloudflare_api_token: nil
  zerossl_eab_hmac_key: nil
  zerossl_eab_kid: nil

vault:
  hostname: nil
  config:
    glues_env: nil

    

grafana:
  hostname: nil
  root_url: nil
  github_client_id: nil
  github_client_secret: nil
  github_org_names: nil
  


argo-cd:
  glueops:
    enabled: false
    apps_cluster_name: nil
    github_client_id: nil
    github_client_secret: nil
    destination_cluster_for_core_apps: "in-cluster"
    ingress_controller_service_type: "LoadBalancer"
    ingress_controller_host_port_enabled: false
  server:
    config: nil
    rbacConfig: nil
    extraArgs:
      - --insecure
    service:
      type: ClusterIP
      annotations:
        external-dns.alpha.kubernetes.io/hostname: nil
    ingress:
      enabled: true
      hosts: nil
      annotations:
        cert-manager.io/cluster-issuer: glueops-cert-zerossl-prod
        kubernetes.io/ingress.class: "internal-ingress-nginx"
      tls: 
        - 
          hosts: 
            - nil
          secretName: echo-tls




