# Default values for glueops-argocd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.



gitHub:
  sshKey: "base64-ssh-key"
  credentialTemplateUrl: "Z2l0QGdpdGh1Yi5jb20=" #git@github.com
  k8sBootstrapRepo: "base64-encoded-string" #git@github.com:GlueOps/platform.git
  customer_github_org_and_team: "org:team"



externalDns:
  cloudflare_api_token: nil


terraformCloudOperator:
  terraform_cloud_api_token: nil
  terraform_cloud_organization_name: nil
  cloud:
    enable:
      aws: false
      gcp: false
    credentials:
      aws:
        AWS_ACCESS_KEY_ID: nil
        AWS_SECRET_ACCESS_KEY: nil
        AWS_REGION: nil
      gcp:
        GOOGLE_CREDENTIALS: nil #base64encoded without any newlines


certManager:
  cloudflare_api_token: nil
  zerossl_eab_hmac_key: nil
  zerossl_eab_kid: nil

vault:
  hostname: nil
  cloud:
    enable:
      aws: false
      gcp: false
    credentials:
      aws:
        AWS_ACCESS_KEY_ID: nil
        AWS_SECRET_ACCESS_KEY: nil
        AWS_REGION: nil
        AWS_KMS_ENDPOINT: nil
      gcp:
        GOOGLE_CREDENTIALS: nil #base64encoded without any newlines
        GOOGLE_PROJECT: nil
        KMS_KEY_RING: nil
        KMS_CRYPTO_KEY: nil
    

grafana:
  hostname: nil
  root_url: nil
  github_client_id: nil
  github_client_secret: nil
  github_org_names: nil
  


argo-cd:
  glueops:
    enabled: false
    apps_cluster_name: nil
    github_client_id: nil
    github_client_secret: nil
    destination_cluster_for_core_apps: "in-cluster"
    ingress_controller_service_type: "LoadBalancer"
    ingress_controller_host_port_enabled: false
  server:
    config: nil
    rbacConfig: nil
    extraArgs:
      - --insecure
    service:
      type: ClusterIP
      annotations:
        external-dns.alpha.kubernetes.io/hostname: nil
    ingress:
      enabled: true
      hosts: nil
      annotations:
        cert-manager.io/cluster-issuer: glueops-cert-zerossl-prod
        kubernetes.io/ingress.class: "internal-ingress-nginx"
      tls: 
        - 
          hosts: 
            - nil
          secretName: echo-tls




