# Default values for glueops-argocd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


glueops_settings:
  domain: nil
  cloud:
    name: nil
    region: nil
    dns: "{{ .Values.glueops_settings.cloud.region }}.{{ .Values.glueops_settings.cloud.name }}.{{ .Values.glueops_settings.domain }}"



gitHub:
  sshKey: "base64-ssh-key"
  credentialTemplateUrl: "Z2l0QGdpdGh1Yi5jb20=" #git@github.com
  k8sBootstrapRepo: "base64-encoded-string" #git@github.com:GlueOps/platform.git



externalDns:
  cloudflare_api_token: nil



certManager:
  cloudflare_api_token: nil
  zerossl_eab_hmac_key: nil
  zerossl_eab_kid: nil

vault:
  hostname: "vault.{{ tpl .Values.glueops_settings.cloud.dns . }}"

grafana:
  hostname: "grafana.{{ tpl .Values.glueops_settings.cloud.dns . }}"
  root_url: nil
  github_client_id: nil
  github_client_secret: nil
  


argo-cd:
  glueops:
    enabled: false
    apps_cluster_name: nil
    github_client_id: nil
    github_client_secret: nil
    destination_cluster_for_core_apps: "in-cluster"
    ingress_controller_service_type: "LoadBalancer"
    ingress_controller_host_port_enabled: false
  server:
    config: nil
    rbacConfig: nil
    extraArgs:
      - --insecure
    service:
      type: ClusterIP
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "argocd.{{ tpl .Values.glueops_settings.cloud.dns . }}"
    ingress:
      enabled: true
      hosts: ["argocd.{{ tpl .Values.glueops_settings.cloud.dns . }}"]
      annotations:
        cert-manager.io/cluster-issuer: glueops-cert-zerossl-prod
        kubernetes.io/ingress.class: "internal-ingress-nginx"
      tls: 
        - 
          hosts: 
            - "argocd.{{ tpl .Values.glueops_settings.cloud.dns . }}"
          secretName: echo-tls




