apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glueops-pull-request-bot
spec:
  destination:
    name: ''
    namespace: glueops-core-pull-request-bot
    server: 'https://kubernetes.default.svc'
  source:
    path: kubernetes/
    repoURL: 'https://github.com/GlueOps/pull-request-bot.git'
    targetRevision: feat/fix-entrypoint
  project: glueops-core
  syncPolicy:
    syncOptions:
      - Replace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
