# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: crunchydata-pgmonitor
#   namespace: glueops-core
# spec:
#   destination:
#     namespace: glueops-core-crunchydata-postgres
#     server: https://kubernetes.default.svc
#   project: glueops-core
#   source:
#     path: kustomize/monitoring
#     repoURL: https://github.com/GlueOps/postgres-operator-examples
#     targetRevision: venkata
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     retry:
#       backoff:
#         duration: 10s
#         factor: 2
#         maxDuration: 3m0s
#       limit: 5