apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-crds
spec:
  destination:
    name: {{ index .Values "argo-cd" "glueops" "destination_cluster_for_core_apps" }}
    namespace: glueops-core-cert-manager
    server: ''
  source:
    path: v1.10.0/
    repoURL: 'https://github.com/GlueOps/cert-manager-crds'
    targetRevision: HEAD
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
