apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    name: in-cluster
    namespace: glueops-core-kube-prometheus-stack
  project: glueops-core
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 39.9.0
    helm:
      skipCrds: true
      values: |-
        grafana:
          # username is 'admin'
          adminPassword: prom-operator
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: internal-ingress-nginx
              cert-manager.io/cluster-issuer: glueops-cert-zerossl-prod
            hosts: ['{{ .Values.grafana.hostname }}']
            path: "/"
            tls:
            - secretName: tls-credential
              hosts:
              - {{ .Values.grafana.hostname }}
          grafana.ini:
            server:
              root_url: "https://{{ .Values.grafana.hostname }}/"
            auth.github:
               enabled: true
               allow_sign_up: true
               scopes: user:email,read:org
               auth_url: https://github.com/login/oauth/authorize
               token_url: https://github.com/login/oauth/access_token
               api_url: https://api.github.com/user
               allowed_organizations: GlueOps
               client_id: {{ .Values.grafana.github_client_id }}
               client_secret: {{ .Values.grafana.github_client_secret }}
            log:
              mode: console
              level: debug
    chart: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
