apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-configuration
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  destination:
    name: {{ index .Values "argo-cd" "glueops" "destination_cluster_for_core_apps" }}
    namespace: glueops-core-tfc-workspaces
  source:
    path: ''
    repoURL: 'https://glueops.github.io/helm-charts'
    targetRevision: 0.8.1
    chart: vault-configuration
    helm:
      parameters:
        - name: GLUEOPS_ENV
          value: {{ .Values.vault.config.glueops_env }}
  project: glueops-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2