apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
spec:
  destination:
    name: in-cluster
    namespace: glueops-core-vault
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    targetRevision: 0.22.0
    chart: vault
    helm:
      values: |-
        # Vault Helm Chart Value Overrides
        global:
          enabled: true
          tlsDisable: false

        injector:
          agentImage:
            tag: "1.12.0"
          enabled: true
          # Use the Vault K8s Image https://github.com/hashicorp/vault-k8s/
          image:
            repository: "hashicorp/vault-k8s"
            tag: "0.14.1"

          resources:
              requests:
                memory: 50Mi
                cpu: 50m
              limits:
                memory: 256Mi
                cpu: 250m
        ui:
          enabled: true
          
        server:
          image:
            tag: "1.12.0"
          ingress:
              activeService: false
              annotations: 
                cert-manager.io/cluster-issuer: glueops-cert-zerossl-prod
                kubernetes.io/ingress.class: internal-ingress-nginx
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              enabled: true
              tls:
                - secretName: vault-ui-tls
                  hosts:
                    - {{ .Values.vault.hostname }}
              hosts: 
                - host: {{ .Values.vault.hostname }}
              
          extraEnvironmentVars:
            VAULT_CACERT: /vault/userconfig/vault-tls/ca.crt
            VAULT_TLSCERT: /vault/userconfig/vault-tls/tls.crt
            VAULT_TLSKEY: /vault/userconfig/vault-tls/tls.key
            {{- if .Values.vault.cloud.enable.gcp }}
            GOOGLE_CREDENTIALS: /vault/userconfig/cloud-kms-credentials/GOOGLE_CREDENTIALS
            {{- end }}
            {{- if .Values.vault.cloud.enable.aws }}
            AWS_REGION: "{{ .Values.vault.cloud.credentials.aws.AWS_REGION | b64dec }}"
            AWS_ACCESS_KEY_ID: "{{ .Values.vault.cloud.credentials.aws.AWS_ACCESS_KEY_ID | b64dec }}"
            AWS_SECRET_ACCESS_KEY: "{{ .Values.vault.cloud.credentials.aws.AWS_SECRET_ACCESS_KEY | b64dec }}"
            AWS_KMS_ENDPOINT: "{{ .Values.vault.cloud.credentials.aws.AWS_KMS_ENDPOINT | b64dec }}"
            {{- end }}

          # extraVolumes is a list of extra volumes to mount. These will be exposed
          # to Vault in the path `/vault/userconfig/<name>/`.
          extraVolumes:
            - type: secret
              name: vault-tls
            {{- if or .Values.vault.cloud.enable.gcp .Values.vault.cloud.enable.aws }}
            - type: secret
              name: cloud-kms-credentials
            {{- end }}

          standalone:
            enabled: false

          # Run Vault in "HA" mode.
          ha:
            enabled: true
            replicas: 3
            raft:
                enabled: true
                setNodeId: true
                config: |
                  ui = true
                  listener "tcp" {
                    address = "0.0.0.0:8200"
                    cluster_address = "0.0.0.0:8201"
                    tls_cert_file = "/vault/userconfig/vault-tls/tls.crt"
                    tls_key_file  = "/vault/userconfig/vault-tls/tls.key"
                    tls_client_ca_file = "/vault/userconfig/vault-tls/ca.crt"
                    tls_min_version = "tls12"
                  }

                  {{- if .Values.vault.cloud.enable.gcp }}
                  seal "gcpckms" {	
                    project     = "{{ .Values.vault.cloud.credentials.gcp.GOOGLE_PROJECT }}"
                    region      = "global"	
                    key_ring    = "{{ .Values.vault.cloud.credentials.gcp.KMS_KEY_RING }}"
                    crypto_key  = "{{ .Values.vault.cloud.credentials.gcp.KMS_CRYPTO_KEY }}"
                  }
                  {{- end }}
                  {{- if .Values.vault.cloud.enable.aws }}
                  seal "awskms" {	
                    kms_key_id     = "alias/hashicorp-vault"
                  }
                  {{- end }}

                  storage "raft" {
                    path = "/vault/data"
                    retry_join {
                      auto_join = "provider=k8s label_selector=\"component=server,app.kubernetes.io/name=vault\" namespace=\"glueops-core-vault\" "
                      leader_tls_servername = "vault-active.glueops-core-vault.svc.cluster.local"
                      leader_client_cert_file = "/vault/userconfig/vault-tls/tls.crt"
                      leader_client_key_file = "/vault/userconfig/vault-tls/tls.key"
                      leader_ca_cert_file = "/vault/userconfig/vault-tls/ca.crt"
                    }

                    autopilot {
                      cleanup_dead_servers = "true"
                      last_contact_threshold = "200ms"
                      last_contact_failure_threshold = "10m"
                      max_trailing_logs = 250000
                      min_quorum = 5
                      server_stabilization_time = "10s"
                    }

                  }

                  service_registration "kubernetes" {}
  project: glueops-core
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      jqPathExpressions:
        - '.webhooks[0].clientConfig.caBundle'
      kind: MutatingWebhookConfiguration
