apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: {{ index .Values "argo-cd" "glueops" "destination_cluster_for_core_apps" }}
    namespace: glueops-core-kube-prometheus-stack
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 45.1.1
    helm:
      skipCrds: true
      values: |-
        # https://github.com/prometheus-operator/prometheus-operator/issues/2890#issuecomment-583006452
        coreDns:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        kubeProxy:
          enabled: false
        alertmanager:
          alertmanagerSpec:
            image:
              registry: ghcr.io
              repository: glueops/alertmanager
              tag: v0.25.0-glueops
            logLevel: debug
            # This externalURL is a hack. Alertmanager will reference back to itself per the code here: https://github.com/prometheus/alertmanager/blob/v0.25.0/template/default.tmpl#L2
            # Example when alert manager renders my hack: 
            # https://grafana.{{ .Values.captain_domain }}/alerting/list
            # - Note: the captain domain does get replaced with the actual captain domain
            externalUrl: https://grafana.{{ .Values.captain_domain }}/alerting/list
        defaultRules:
          disabled:
            KubePodNotReady: true
        prometheus: 
          prometheusSpec:
            ruleSelector: {}
            ruleNamespaceSelector: {}
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelector: {}
            podMonitorNamespaceSelector: {}
            podMonitorSelectorNilUsesHelmValues: false
            logLevel: debug
        grafana:
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: internal-ingress-nginx
            hosts: ['grafana.{{ .Values.captain_domain }}']
            path: "/"
          additionalDataSources:
          - name: Loki
            type: loki
            url: {{ .Values.grafana.loki_data_source_domain }}
          - name: Alertmanager
            type: alertmanager
            jsonData:
              implementation: prometheus
            url: "http://kube-prometheus-stack-alertmanager.glueops-core-kube-prometheus-stack:9093/"
          grafana.ini:
            server:
              root_url: "https://grafana.{{ .Values.captain_domain }}/"
            security:
              disable_initial_admin_creation: true
            auth.github:
               enabled: true
               allow_sign_up: true
               scopes: user:email,read:org
               auth_url: https://github.com/login/oauth/authorize
               token_url: https://github.com/login/oauth/access_token
               api_url: https://api.github.com/user
               allowed_organizations: {{ .Values.grafana.github_admin_org_name }} {{ .Values.grafana.github_other_org_names }}
               role_attribute_path: contains(groups[*], '@{{ .Values.grafana.github_admin_org_name }}/{{ .Values.grafana.github_admin_team_name }}') && 'Admin' || 'Viewer'
               client_id: {{ .Values.grafana.github_client_id }}
               client_secret: {{ .Values.grafana.github_client_secret }}
    chart: kube-prometheus-stack
