apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: {{ index .Values "argo-cd" "glueops" "destination_cluster_for_core_apps" }}
    namespace: glueops-core-external-dns
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 6.12.0
    chart: external-dns
    helm:
      parameters:
        - name: aws.credentials.secretKey
          value: {{ .Values.externalDns.aws_secretKey }}
        - name: aws.credentials.accessKey
          value: {{ .Values.externalDns.aws_accessKey }}
        - name: aws.region
          value: {{ .Values.externalDns.aws_region }}
        - name: provider
          value: aws
        - name: aws.preferCNAME
          value: "true"
        - name: metrics.enabled
          value: "true"
        - name: metrics.serviceMonitor.enabled
          value: "true"
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5