apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glueops-alerts
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  destination:
    name: {{ index .Values "argo-cd" "glueops" "destination_cluster_for_core_apps" }}
    namespace: glueops-core-kube-prometheus-stack
  project: glueops-core
  syncPolicy:
    syncOptions:
      - Replace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    path: ''
    repoURL: 'https://helm.gpkg.io/platform'
    targetRevision: 0.1.0
    helm:
      skipCrds: true
      parameters:
        - name: prometheus-alertmanagerconfig-opsgenie.opsgenie.apikey
          value: {{ .Values.glueops_alerts.opsgenie_apikey }}
    chart: glueops-prometheus-alerts
  project: glueops-core
