apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    name: {{ index .Values "argo-cd" "glueops" "destination_cluster_for_core_apps" }}
    namespace: glueops-core-kube-prometheus-stack
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 45.1.1
    helm:
      skipCrds: true
      parameters:
        - name: prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues
          value: 'false'
        - name: prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues
          value: 'false'
      values: |-
        grafana:
          # username is 'admin'
          adminPassword: prom-operator
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: internal-ingress-nginx
            hosts: ['grafana.{{ .Values.captain_domain }}']
            path: "/"
          additionalDataSources:
          - name: Loki
            type: loki
            url: {{ .Values.grafana.loki_data_source_domain }}
          grafana.ini:
            server:
              root_url: "https://grafana.{{ .Values.captain_domain }}/"
            auth.github:
               enabled: true
               allow_sign_up: true
               scopes: user:email,read:org
               auth_url: https://github.com/login/oauth/authorize
               token_url: https://github.com/login/oauth/access_token
               api_url: https://api.github.com/user
               allowed_organizations: {{ .Values.grafana.github_org_names }}
               client_id: {{ .Values.grafana.github_client_id }}
               client_secret: {{ .Values.grafana.github_client_secret }}
    chart: kube-prometheus-stack
