apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  destination:
    name: {{ index .Values "argo-cd" "glueops" "destination_cluster_for_core_apps" }}
    namespace: glueops-core-external-dns
    server: ''
  source:
    path: ''
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 6.9.0
    chart: external-dns
    helm:
      parameters:
        - name: cloudflare.apiToken
          value: {{ .Values.externalDns.cloudflare_api_token }}
        - name: provider
          value: cloudflare
  project: glueops-core
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        maxDuration: 3m0s
        factor: 2
