apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-prerequisites
  annotations:
    argocd.argoproj.io/sync-wave: "3"  
spec:
  destination:
    name: {{ index .Values "argo-cd" "glueops" "destination_cluster_for_core_apps" }}
    namespace: glueops-core-vault
  project: glueops-core
  source:
    chart: glueops-vault-prerequisites
    helm:
      parameters:
      - name: UNUSED_VALUE
        value: "bmls"
    repoURL: https://glueops.github.io/platform-helm-charts
    targetRevision: 0.1.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m0s
      limit: 5
    syncOptions:
    - CreateNamespace=true