---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: glueops-core
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: {{ index .Values "argo-cd" "glueops" "apps_cluster_name" }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-4.8.2
data:
  #exec.enabled: "true" https://argo-cd.readthedocs.io/en/stable/operator-manual/web_based_terminal/
  url: https://argocd.gcp.glueops.rocks
  dex.config: |
    connectors:
      # GitHub GlueOps
      - type: github
        id: github
        name: GitHub
        config:
          clientID: {{ index .Values "argo-cd" "glueops" "github_client_id" }}
          clientSecret: {{ index .Values "argo-cd" "glueops" "github_client_secret" }}
          orgs:
          - name: GlueOps
            teams:
            - argocd_super_admins
          - name: demo-antoniostacos
            teams:
            - developers
          # Flag which indicates that all user groups and teams should be loaded.
          loadAllGroups: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: glueops-core
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: {{ index .Values "argo-cd" "glueops" "apps_cluster_name" }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    helm.sh/chart: argo-cd-4.8.2
data:
  # TODO - add project-level RBAC when argo 2.5.0 is released (https://github.com/argoproj/argo-cd/issues/9464)
  policy.csv: |
    g, GlueOps:argocd_super_admins, role:admin
    g, demo-antoniostacos:developers, role:developers
    p, role:developers, clusters, get, *, allow
    p, role:developers, *, get, antonios-developers-project, allow
    p, role:developers, repositories, *, *, allow
    p, role:developers, applications, *, antonios-developers-project/*, allow
    p, role:developers, exec, *, antonios-developers-project/*, allow
