apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-nginx-default-certs
spec:
  dnsNames:
  - '*.apps.{{ .Values.captain_domain }}'
  - '*.{{ .Values.captain_domain }}'
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: glueops-cert-zerossl-prod
  secretName: ingress-nginx-default-certs