apiVersion: v1
data:
  name: aGVsbS1jaGFydHM=
  project: ZGV2ZWxvcG1lbnQ=
  type: aGVsbQ==
  url: aHR0cHM6Ly9nbHVlb3BzLmdpdGh1Yi5pby9oZWxtLWNoYXJ0cw==
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: glueops-public-helm-charts
type: Opaque