apiVersion: v1
data:
  name: aGVsbS1jaGFydHM=
  project: ZGV2ZWxvcG1lbnQ=
  type: aGVsbQ==
  url: aHR0cHM6Ly9nbHVlb3BzLmdpdGh1Yi5pby9oZWxtLWNoYXJ0cw==
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: glueops-public-helm-charts
type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  roles:
  - description: {{ .Values.gitHub.customer_github_org_and_team }}
    groups:
    - "{{ .Values.gitHub.customer_github_org_and_team }}"
    name: developers
  sourceRepos:
  - https://glueops.github.io/helm-charts
