# apiVersion: v1
# data:
#   sshPrivateKey: {{ .Values.gitHub.sshKey }}
#   url: {{ .Values.gitHub.credentialTemplateUrl }}
# kind: Secret
# metadata:
#   annotations:
#     managed-by: argocd.argoproj.io
#   labels:
#     argocd.argoproj.io/secret-type: repo-creds
#   name: creds-github-ssh-key
# ---
apiVersion: v1
data:
  project: Z2x1ZW9wcy1jb3Jl #glueops-core
  type: Z2l0 #git
  url: {{ .Values.gitHub.k8sBootstrapRepo }}
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-github-k8s-cluster-bootstrap-via-argocd
type: Opaque
---
apiVersion: v1
data:
  project: Z2x1ZW9wcy1jb3Jl #glueops-core
  type: aGVsbQ== #helm
  url: aHR0cHM6Ly9nbHVlb3BzLmdpdGh1Yi5pby9wbGF0Zm9ybS1oZWxtLWNoYXJ0cw== #https://glueops.github.io/platform-helm-charts
kind: Secret
metadata:
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: repository
  name: repo-helm-glueops-public
type: Opaque
